name: Generate AWG Configs

on:
  workflow_dispatch:
    inputs:
      jumlah:
        description: "Jumlah config"
        required: true
        default: "3"
        type: string

      ip_awal:
        description: "IP awal client"
        required: true
        default: "10.66.66.61"
        type: string

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y wireguard-tools zip

      - name: Generate AWG configs
        env:
          JUMLAH: ${{ inputs.jumlah }}
          IP_AWAL: ${{ inputs.ip_awal }}
          ENDPOINT: "103.235.72.131:16978"
          SERVER_PUBLIC_KEY: "692CvI8V+exhrfBzofx1innWxsDDRA2eHuDcT6GpLVE="
        run: |
          set -e

          mkdir -p AWG_CONFIGS

          IFS='.' read -r A B C D <<< "$IP_AWAL"

          for ((i=0; i<JUMLAH; i++)); do

            IP="$A.$B.$C.$((D+i))"

            PRIVATE_KEY=$(wg genkey)
            PUBLIC_KEY=$(printf '%s' "$PRIVATE_KEY" | wg pubkey)

            PSK=$(wg genpsk)

            NAME="CLIENT_$((i+1))"

            cat > "AWG_CONFIGS/${NAME}.conf" <<EOF
          [Interface]
          PrivateKey = $PRIVATE_KEY
          Address = ${IP}/24
          DNS = 1.1.1.1,8.8.8.8

          Jc = 4
          Jmin = 40
          Jmax = 70
          S1 = 50
          S2 = 100
          H1 = 2112615044
          H2 = 3641400900
          H3 = 4133943628
          H4 = 3466609064

          [Peer]
          PublicKey = $SERVER_PUBLIC_KEY
          PresharedKey = $PSK
          Endpoint = $ENDPOINT
          AllowedIPs = 0.0.0.0/0, ::/0
          PersistentKeepalive = 25
          EOF

            echo "================================"
            echo "$NAME"
            echo "IP         : $IP"
            echo "PublicKey  : $PUBLIC_KEY"
            echo "================================"

          done

          zip -r AWG_CONFIGS.zip AWG_CONFIGS

      - name: Upload ZIP
        uses: actions/upload-artifact@v4
        with:
          name: AWG_CONFIGS
          path: AWG_CONFIGS.zip
          retention-days: 1
